import ButtonNavBar from '@/components/layout/navbar';
import '../globals.css'
import { AuthProvider } from "@/provider/providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`antialiased bg-wh`}>
       <AuthProvider>  {children} 
        
        <ButtonNavBar/>
        </AuthProvider> 
      </body>
    </html>
  );
}
